from .attendence import Attendance
from .subject import Subject
from .class_section import ClassSection
from .class_subject import ClassSubject
from .department import Department
from .lecture import Lecture
from .student import Student
from .teacher import Teacher
from .tenant import Tenant
from .time_table import Timetable
